---
name: dns-publisher

releases:
- name: dns-publisher
  version: v2
  url: https://github.com/a2geek/dns-publisher-release/releases/download/v2/dns-publisher-release.tgz
  sha1: 8ef7737ad98616d71053c63efcebcc9ad312916d

instance_groups:
- name: dns-publisher
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: dns-publisher
    release: dns-publisher
    properties:
      mappings:
      - instance-group: web
        deployment: concourse
        fqdns: [concourse.lan]
      - instance-group: postgres
        deployment: postgres
        fqdns: [postgres.lan]
      - instance-group: router
        deployment: cf
        fqdns: [alias.cf.lan, "*.sys.cf.lan", "*.app.cf.lan"]
      publisher:
        type: openwrt
        dry-run: "false"
        options:
          strategy: "dhcp-dnsmasq-address"
          user: root
          host: 192.168.1.1
          private-key: ((openwrt.private_key))

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false
