---
name: dns-publisher

releases:
- name: dns-publisher
  version: latest

instance_groups:
- name: dns-publisher
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: dns-publisher
    release: dns-publisher
    properties:
      mappings:
      - instance-group: concourse
        deployment: concourse
        fqdn: concourse.lan
      - instance-group: postgres
        deployment: postgres
        fqdn: postgres.lan
      - instance-group: router
        deployment: cf
        fqdn: alias.cf.lan
      publisher:
        type: openwrt
        dry-run: "false"
        options:
          user: root
          host: 192.168.1.1
          private-key: ((openwrt.private_key))

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false
