---
name: dns-publisher

releases:
- name: dns-publisher
  version: v5
  url: https://github.com/a2geek/dns-publisher-release/releases/download/v5/dns-publisher-release.tgz
  sha1: 56c37ecf4527fb7a1d10c7ca62e5fd8c208d0b9f

instance_groups:
- name: dns-publisher
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: dns-publisher
    release: dns-publisher
    properties:
      log-level: info

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false
