---
name: dns-publisher

releases:
- name: dns-publisher
  version: v6
  url: https://github.com/a2geek/dns-publisher-release/releases/download/v6/dns-publisher-release.tgz
  sha1: fdfc2fc4169ae84b869c4118a1c62db6df282c93

instance_groups:
- name: dns-publisher
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: dns-publisher
    release: dns-publisher
    properties:
      log-level: info

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false
