---
name: dns-publisher

releases:
- name: dns-publisher
  version: v3
  url: https://github.com/a2geek/dns-publisher-release/releases/download/v3/dns-publisher-release.tgz
  sha1: 8d97691691f17abf7d87efc6b559c9a625fd35b3

instance_groups:
- name: dns-publisher
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: dns-publisher
    release: dns-publisher
    properties:
      log-level: info
      bosh-dns:
        mappings:
        - instance-group: web
          deployment: concourse
          fqdns: [concourse.lan]
        - instance-group: haproxy
          deployment: cf
          fqdns: ["*.sys.cf.lan", "*.app.cf.lan"]
        - instance-group: gitea
          deployment: gitea
          fqdns: [gitea.gdc.lan]
        - instance-group: jumpbox
          deployment: jumpbox
          fqdns: [jumpbox.gdc.lan]
      cloud-foundry:
        trigger:
          refresh: 1m
        url: https://api.sys.cf.lan
        skip-ssl-validation: true
        client-id: testapp
        client-secret: testpw
        alias: "alias.sys.cf.lan"
        mappings: ["*.cf.lan"]
      publisher:
        type: openwrt
        dry-run: "false"
        options:
          strategy: "dhcp-dnsmasq-address"
          user: root
          host: 192.168.1.1
          private-key: ((openwrt.private_key))

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false
